version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  opentelemetry-collector:
    image: otel/opentelemetry-collector
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    container_name: opentelemetry-collector
    ports:
      - 8888:8888
      - 8889:8889
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    ports:
      - 3000:3000
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  prometheus_data:
  grafana_storage:


networks:
  monitoring:
