apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: monitoring
data:
  collector.yaml: |-
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              params:
                format: [prometheus]
              honor_labels: true
              static_configs:
                - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080'] 
            - job_name: 'node-exporter'
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
              - source_labels: [__meta_kubernetes_endpoints_name]
                regex: 'node-exporter'
                action: keep 

    processors:
      batch:
        send_batch_size: 10000
        timeout: 5s

    exporters:
      prometheus:
        endpoint: ":8090"
      logging:
        loglevel: debug

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus, logging]
