prometheusOperator:
  enabled: true


defaultRules:
  create: false

grafana:
  enabled: false


alertmanager:
  enabled: true
  config:
      route:
        group_by: ['namespace']
        group_wait: 1s
        group_interval: 5m
        repeat_interval: 1h
        receiver: 'webhook-receiver'
        routes:
        - receiver: 'webhook-receiver'
          matchers:
            - alertname = "Watchdog"
      receivers:
      - name: 'webhook-receiver'
        webhook_configs:
            - url: 'http://10.208.99.102:5000/alert'  #send to a deceision engine or event-handler the alert
             
  service:
    type: NodePort
    nodePort: 31000

      

# Disable collect data from kubernetes components
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubelet:
  enabled: false

kubeApiServer:
  enabled: false  

coreDns:
  enabled: false

# Settings Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    maximumStartupDurationSeconds: 120

    # Enable PVC
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: fast
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 1Gi
    ruleSelector:
      matchLabels:
        role: example-rules


  service:
    type: NodePort
    nodePort: 30000
    port: 9090

  # Disable monitors (not necessary)
  serviceMonitorSelector: {} 
  podMonitorSelector: {}      

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false
